title: 潘尚的个人博客
home: 潘尚
paginate: 8
email: shinepans@live.com 574273250@qq.com
production_url: http://panshang.xyz
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://panshang.xyz" # the base hostname & protocol for your site
permalink: /:year:month:day.html

# Build settings
highlighter: pygments
markdown: kramdown  # [ maruku | rdiscount | kramdown | redcarpet ]

kramdown:
  input:          GFM
  auto_ids:       true
  auto_id_prefix: 'id-'

# 网站描述
description:   Web 全栈开发 邮箱：shinepans@live.com 574273250@qq.com
# 用户名，用来显示自己相关网络账号信息的。about.md之中。
username: Panshang

user:
  email: shinepans@live.com
  github: http://github.com/shinepans
  weibo: http://weibo.com/shinespy
  twitter: http://twitter.com/shinepans1
  weixin: 574273250
  desc: web全栈开发，有轻度的强迫症，酷爱编程。

# 这里替换成线上的静态资源的链接。 主要最后的"/"。也要注意css使用的字体的链接。
pub:
  css: http://7xq5e5.com1.z0.glb.clouddn.com/css/
  js: http://7xq5e5.com1.z0.glb.clouddn.com/js/
  image: http://7xq5e5.com1.z0.glb.clouddn.com/pub/

# 这里是本地的静态资源存放的路径
dev:
  css: /assets/css/
  js: /assets/js/
  image: /assets/images/

# 选择模式 开发模式还是发布模式。上线之前务必改成pub！
model: pub

